name: Build Project

on:
  push:
    branches:
    - 'dev/*'
    tags:
    - '*'
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload to Discord (If dev branch)
        if: startsWith(github.ref, 'refs/heads/dev/')
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: ./gradlew discordupload
      - name: Configure AWS Credentials
        if: startsWith(github.ref, 'refs/heads/dev/') || startsWith(github.ref, 'refs/heads/dev/')
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
      - name: Publish to Maven (If dev or release)
        if: startsWith(github.ref, 'refs/heads/dev/') || startsWith(github.ref, 'refs/heads/dev/')
        run: ./gradlew publish
      - name: Publish to Curseforge (If tagged)
        if: startsWith(github.ref, 'refs/tags/')
        env:
          CURSE_API: ${{ secrets.CURSE_API }}
        run: ./gradlew curseforge
